[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
redirect_stderr=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:clp-nginx]
command=/usr/sbin/clp-nginx -g "daemon off;" -c /etc/cloudpanel/services/clp-nginx/nginx.conf
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:php-fpm7.1]
command=/usr/sbin/php-fpm7.1 -F --fpm-config /etc/php/7.1/fpm/php-fpm.conf
numprocs=1
autostart=false
autorestart=true
stopsignal=KILL

[program:php-fpm7.2]
command=/usr/sbin/php-fpm7.2 -F --fpm-config /etc/php/7.2/fpm/php-fpm.conf
numprocs=1
autostart=false
autorestart=true
stopsignal=KILL

[program:php-fpm7.3]
command=/usr/sbin/php-fpm7.3 -F --fpm-config /etc/php/7.3/fpm/php-fpm.conf
numprocs=1
autostart=false
autorestart=true
stopsignal=KILL

[program:php-fpm7.4]
command=/usr/sbin/php-fpm7.4 -F --fpm-config /etc/php/7.4/fpm/php-fpm.conf
numprocs=1
autostart=false
autorestart=true
stopsignal=KILL

[program:php-fpm8.0]
command=/usr/sbin/php-fpm8.0 -F --fpm-config /etc/php/8.0/fpm/php-fpm.conf
numprocs=1
autostart=false
autorestart=true
stopsignal=KILL

[program:php-fpm8.1]
command=/usr/sbin/php-fpm8.1 -F --fpm-config /etc/php/8.1/fpm/php-fpm.conf
numprocs=1
autostart=false
autorestart=true
stopsignal=KILL

[program:php-fpm8.2]
command=/usr/sbin/php-fpm8.2 -F --fpm-config /etc/php/8.2/fpm/php-fpm.conf
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:php-fpm8.3]
command=/usr/sbin/php-fpm8.3 -F --fpm-config /etc/php/8.3/fpm/php-fpm.conf
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:clp-php-fpm]
command=/usr/sbin/clp-php-fpm -F -y /etc/cloudpanel/services/clp-php/fpm/php-fpm.conf -c /etc/cloudpanel/services/clp-php/fpm/php.ini
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:mysql]
command=/usr/bin/pidproxy /var/run/mysqld/mysqld.pid /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:elasticsearch]
command=/usr/share/elasticsearch/bin/elasticsearch
user=elasticsearch
environment=ES_HEAP_SIZE=2G
autostart=true
autorestart=true
stopsignal=KILL

[program:varnish]
command=/usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T :6082 -f /etc/varnish/default.vcl -s malloc,1G -p http_resp_hdr_len=40000
autostart=true
autorestart=true
stopsignal=KILL

[program:rabbitmq]
command=/usr/sbin/rabbitmq-server
numprocs=1
autostart=true
autorestart=true

[program:redis-server]
command=/usr/bin/redis-server /etc/redis/redis.conf
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:clp-redis-server]
command=/usr/bin/redis-server /etc/cloudpanel/services/clp-redis-server/redis.conf
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:cron]
command=/usr/sbin/cron -f
numprocs=1
autostart=true
autorestart=true
stopsignal=KILL

[program:postfix]
command=/etc/init.d/postfix restart
startsecs=0
autostart=false
autorestart=false

[program:rsyslog]
command=/usr/sbin/rsyslogd -n